name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R package dependencies
      run: |
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        R -e 'install.packages("rsconnect")'
        R -e 'rsconnect::setAccountInfo(name="fabio-favoretto", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
        R -e 'rsconnect::deployApp(appDir = ".", appName = "revillagigedo_app")'
